version: '3'
services:
   php-fpm:
     build: 
      args:
        user: saitam
        uid: 1000
      context: ./php8-fpm
     container_name: php8-fpm
     volumes:
       - ./src:/var/www/html
       - ./php8-fpm/config/jit.ini:/usr/local/etc/php/conf.d/jit.ini
       - ./php8-fpm/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini

   nginx:
     build: ./nginx
     restart: always
     ports:
       - "80:80"
     volumes:
       - "./src:/var/www/html"
       - "./nginx/default:/etc/nginx/conf.d/default.conf"
     depends_on:
       - php-fpm

   db:
     image: mysql:8.0
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: secret
     volumes:
       - "./db:/var/lib/mysql"

   adminer:
     image: adminer
     restart: always
     ports:
       - 8080:8080

